### ISSUE TITLE
Change inherit_properties behavior to be inclusive

### ISSUE THREAD

**Issue by pedrohr** [saezlab/BioCypher#110]
We would like to suggest a change in the `inherit_properties` behavior to include the properties of the parent class in the subclass properties as opposed to replacing them entirely.

For example:
```
region:
  represented_as: node
  properties:
    chromosome: str
    position_start: int
    position_end: int

gene:
  is_a: region
  inherit_properties: true
  properties:
    gene_name: int

variant:
  is_a: region
  inherit_properties: true
  properties:
    ref: str
    alt: str
```

In this case, we would expect to `gene` and `variant` to have the properties of the parent class `region` (`chromosome`, `position_start`, `position_end`). The current behavior is replacing the properties of the subclasses.
