### ISSUE TITLE
Split up namespace prefix and identifier field?

### ISSUE THREAD

**Issue by slobentanzer** [saezlab/BioCypher#69]

**Comment by slobentanzer** [comment]
@vincentvialard suggested to move to the following syntax:
```
protein:
  represented_as: node
  subclasses:
    - preferred_id: uniprot
      label_in_input: uniprot_protein
    - preferred_id: entrez
      label_in_input: entrez_protein
```

allowing also merging of input labels for each subclass:
```
protein:
  represented_as: node
  subclasses:
    - preferred_id: uniprot
      label_in_input: [uniprot_protein, another_protein]
    - preferred_id: entrez
      label_in_input: entrez_protein
```

**Comment by slobentanzer** [comment]
To solve both problems, i would suggest the following addition:
```
sequence variant:
  represented_as: node
  subclasses:
    - label: clinically relevant 
      preferred_id: clinvar
      label_in_input: clinically_relevant_variant
    - label: somatic
      preferred_id: clinvar
      label_in_input: [known_variant, somatic_variant]
```

This is an explicit way of defining subclasses, so I would not call this implicit subclassing any more. The original "implicit subclassing" syntax can remain being usable as a shorthand for a special case of this new, more powerful, but also more error-prone syntax.

**Comment by vincentvialard** [comment]
It should be decided if subclasses can be used in combination with the main class or not:
```
protein:
  represented_as: node
  preferred_id: mainprot
  label_in_input: main_protein
  subclasses:
    - preferred_id: uniprot
      label_in_input: [uniprot_protein, another_protein]
    - preferred_id: entrez
      label_in_input: entrez_protein
```
