### ISSUE TITLE
Problem about multiple edge types between same source and target node

### ISSUE THREAD

**Issue by bnymnsen** [saezlab/BioCypher#86]
Hi Sebastian, 

We are trying to create Protein-Go edges for our database. In our data, there are multiple edge types between same source and target node. However, as far as I look, BioCypher doesn't support generating these edge types. For example, I tried 2 different approaches in the config file to generate these edges.

First one:
```
protein to cellular component association:
  #is_a: macromolecular machine to cellular component association
  represented_as: edge
  label_as_edge: [Located_in, Part_of, Is_active_in]
  preferred_id: go
  source: protein
  target: cellular component
  label_in_input: [Located_in, Part_of, Is_active_in]
  properties:
    reference: str
    evidence_code: str
```

Second one:
```
protein to cellular component association:
  #is_a: macromolecular machine to cellular component association
  represented_as: edge
  label_as_edge: Located_in
  preferred_id: go
  source: protein
  target: cellular component
  label_in_input: Located_in
  properties:
    reference: str
    evidence_code: str
    
protein to cellular component association:
  #is_a: macromolecular machine to cellular component association
  represented_as: edge
  label_as_edge: Part_of
  preferred_id: go
  source: protein
  target: cellular component
  label_in_input: Part_of
  properties:
    reference: str
    evidence_code: str
    
protein to cellular component association:
  #is_a: macromolecular machine to cellular component association
  represented_as: edge
  label_as_edge: Is_active_in
  preferred_id: go
  source: protein
  target: cellular component
  label_in_input: Is_active_in
  properties:
    reference: str
    evidence_code: str
```

I also tried to do some changes in BioCypher's code to patch the problem, but I realized that many things had to be changed to fix this problem.
